/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PostBriefingRouteImport } from './routes/post-briefing'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsIdRouteImport } from './routes/agents.$id'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCrewPhotoSlugRouteImport } from './routes/api/crew-photo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewRoute = CrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PostBriefingRoute = PostBriefingRouteImport.update({
  id: '/post-briefing',
  path: '/post-briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AgentsRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCrewPhotoSlugRoute = ApiCrewPhotoSlugRouteImport.update({
  id: '/api/crew-photo/$slug',
  path: '/api/crew-photo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/post-briefing': typeof PostBriefingRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/agents/$id': typeof AgentsIdRoute
  '/c/$slug': typeof CSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/crew-photo/$slug': typeof ApiCrewPhotoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/post-briefing': typeof PostBriefingRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/agents/$id': typeof AgentsIdRoute
  '/c/$slug': typeof CSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/agents': typeof AgentsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/crew-photo/$slug': typeof ApiCrewPhotoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRouteWithChildren
  '/crew': typeof CrewRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/post-briefing': typeof PostBriefingRoute
  '/post-job': typeof PostJobRoute
  '/profile': typeof ProfileRoute
  '/agents/$id': typeof AgentsIdRoute
  '/c/$slug': typeof CSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/agents/': typeof AgentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/crew-photo/$slug': typeof ApiCrewPhotoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/crew'
    | '/dashboard'
    | '/documents'
    | '/jobs'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/post-briefing'
    | '/post-job'
    | '/profile'
    | '/agents/$id'
    | '/c/$slug'
    | '/jobs/$id'
    | '/news/$slug'
    | '/agents/'
    | '/jobs/'
    | '/news/'
    | '/api/auth/$'
    | '/api/crew-photo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crew'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/onboarding'
    | '/post-briefing'
    | '/post-job'
    | '/profile'
    | '/agents/$id'
    | '/c/$slug'
    | '/jobs/$id'
    | '/news/$slug'
    | '/agents'
    | '/jobs'
    | '/news'
    | '/api/auth/$'
    | '/api/crew-photo/$slug'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/crew'
    | '/dashboard'
    | '/documents'
    | '/jobs'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/post-briefing'
    | '/post-job'
    | '/profile'
    | '/agents/$id'
    | '/c/$slug'
    | '/jobs/$id'
    | '/news/$slug'
    | '/agents/'
    | '/jobs/'
    | '/news/'
    | '/api/auth/$'
    | '/api/crew-photo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  CrewRoute: typeof CrewRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PostBriefingRoute: typeof PostBriefingRoute
  PostJobRoute: typeof PostJobRoute
  ProfileRoute: typeof ProfileRoute
  CSlugRoute: typeof CSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCrewPhotoSlugRoute: typeof ApiCrewPhotoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew': {
      id: '/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof CrewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-briefing': {
      id: '/post-briefing'
      path: '/post-briefing'
      fullPath: '/post-briefing'
      preLoaderRoute: typeof PostBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/$id': {
      id: '/agents/$id'
      path: '/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/crew-photo/$slug': {
      id: '/api/crew-photo/$slug'
      path: '/api/crew-photo/$slug'
      fullPath: '/api/crew-photo/$slug'
      preLoaderRoute: typeof ApiCrewPhotoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsRouteChildren {
  AgentsIdRoute: typeof AgentsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsIdRoute: AgentsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRouteWithChildren,
  CrewRoute: CrewRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PostBriefingRoute: PostBriefingRoute,
  PostJobRoute: PostJobRoute,
  ProfileRoute: ProfileRoute,
  CSlugRoute: CSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCrewPhotoSlugRoute: ApiCrewPhotoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
